version: '3'
services:
  postgres:
    container_name: postgres
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge