version: '3'
services:
  postgres:
    container_name: postgres
    image: "postgres:latest"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authentication
      PGDATA: /data/postgres
#    volumes:
#      - postgres:/data/postgres
    ports:
      - "5432:5432"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-user}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-pass}
    ports:
      - "5672:5672"
      - "15672:15672"
networks:
  postgres:
    driver: bridge