server:
  port: 8080

service:
  authentication:
    http://localhost:8083
  user:
    http://localhost:8082
  host:
    http://localhost:8084
  accommodation:
    http://localhost:8086
  reservation:
    http://localhost:8087
  search:
    http://localhost:8090

headers:
  jwt-header: 'Authorization'
  jwt-prefix: 'Bearer '
  xsrf-token-header: 'XSRF-TOKEN'
  xsrf-cookie-header: 'X-XSRF-TOKEN'

jwt-secret-key: ${SECRET_KEY:VCinmKpfoFsGBQmBlJet9RLamlZQJa2i}
