spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/user}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:username}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
